// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myria.Server.Realm.Data;

#nullable disable

namespace Myria.Server.Realm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Myria.Server.Realm.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockedCharacterId");

                    b.HasIndex("BlockerCharacterId", "BlockedCharacterId")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessoryItemId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveJobId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmorItemId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpForNextLvl")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryPages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastClassChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastClassPenaltyApplied")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastHealerRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastJobChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSaved")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MoneyBronze")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MoneyCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PotionTierAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RaceSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatBaseHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatBaseMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatDexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatDexterityBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatEndurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatEnduranceBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatIntelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatIntelligenceBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpirit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpiritBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatStrength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatStrengthBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatUnusedPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponItemId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterActiveQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemProgressJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KillProgressJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterActiveQuests");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterClassXp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterClassXp");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCombinedSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStashed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StashedForClass")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterCombinedSkills");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCombinedSkillInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombinedSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CombinedSkillId");

                    b.ToTable("CharacterCombinedSkillInputs");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCompletedQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterCompletedQuests");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCompositeSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStashed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StashedForClass")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterCompositeSkills");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCompositeSkillComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompositeSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompositeSkillId");

                    b.ToTable("CharacterCompositeSkillComponents");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterInventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StackSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterInventoryItems");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FameXp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("KnowledgeXp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastFameTickDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSkillUsedDay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SkillXp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterJobs");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterKnownRune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseRuneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterKnownRunes");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRepeatableQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionsToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterRepeatableQuests");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRoomGathering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastGatheredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterRoomGathering");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRuneAddedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnownRuneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KnownRuneId");

                    b.ToTable("CharacterRuneAddedWords");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRuneDictEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOfficiallyLearned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterRuneDictionary");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterSkillSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSkillSlots");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddresseeCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequesterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeCharacterId");

                    b.HasIndex("RequesterCharacterId", "AddresseeCharacterId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaderCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaderCharacterId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicantCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantCharacterId");

                    b.HasIndex("GuildId", "ApplicantCharacterId")
                        .IsUnique();

                    b.ToTable("GuildApplications");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ItemId")
                        .IsUnique();

                    b.ToTable("GuildDeposits");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildHouseListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AskingPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildPropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ListedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerGuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildPropertyId")
                        .IsUnique();

                    b.HasIndex("SellerGuildId");

                    b.ToTable("GuildHouseListings");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviteeCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRookieInvite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InviteeCharacterId");

                    b.HasIndex("InviterCharacterId");

                    b.HasIndex("GuildId", "InviteeCharacterId")
                        .IsUnique();

                    b.ToTable("GuildInvites");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildMember", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BaseAnchorRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CityRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PricePaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildProperties");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildRookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecruiterCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RecruiterCharacterId");

                    b.HasIndex("GuildId", "CharacterId")
                        .IsUnique();

                    b.ToTable("GuildRookies");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BuiltAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildPropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuilt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinRankRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildPropertyId");

                    b.ToTable("GuildRooms");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildSettings", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepositWithdrawMinRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildTreasury", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildTreasuries");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.PlayerShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCharacterId")
                        .IsUnique();

                    b.ToTable("PlayerShops");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.PlayerShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerShopId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerShopId", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerShopItems");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Block", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "BlockedCharacter")
                        .WithMany()
                        .HasForeignKey("BlockedCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Character", "BlockerCharacter")
                        .WithMany()
                        .HasForeignKey("BlockerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlockedCharacter");

                    b.Navigation("BlockerCharacter");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterActiveQuest", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("ActiveQuests")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterClassXp", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("ClassXp")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCombinedSkill", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("CombinedSkills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCombinedSkillInput", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.CharacterCombinedSkill", "CombinedSkill")
                        .WithMany("Inputs")
                        .HasForeignKey("CombinedSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombinedSkill");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCompletedQuest", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("CompletedQuests")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCompositeSkill", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("CompositeSkills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCompositeSkillComponent", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.CharacterCompositeSkill", "CompositeSkill")
                        .WithMany("Components")
                        .HasForeignKey("CompositeSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompositeSkill");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterInventoryItem", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterJob", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("Jobs")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterKnownRune", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("KnownRunes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRepeatableQuest", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("RepeatableQuests")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRoomGathering", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("RoomGatheringStatus")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRuneAddedWord", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.CharacterKnownRune", "KnownRune")
                        .WithMany("AddedWords")
                        .HasForeignKey("KnownRuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownRune");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterRuneDictEntry", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("RuneDictionary")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterSkill", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterSkillSlot", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany("SkillSlots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Friendship", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "AddresseeCharacter")
                        .WithMany()
                        .HasForeignKey("AddresseeCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Character", "RequesterCharacter")
                        .WithMany()
                        .HasForeignKey("RequesterCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddresseeCharacter");

                    b.Navigation("RequesterCharacter");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Guild", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "LeaderCharacter")
                        .WithMany()
                        .HasForeignKey("LeaderCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaderCharacter");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildApplication", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "ApplicantCharacter")
                        .WithMany()
                        .HasForeignKey("ApplicantCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithMany("Applications")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicantCharacter");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildDeposit", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithMany("Deposit")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildHouseListing", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.GuildProperty", "GuildProperty")
                        .WithOne("Listing")
                        .HasForeignKey("Myria.Server.Realm.Models.GuildHouseListing", "GuildPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Guild", "SellerGuild")
                        .WithMany()
                        .HasForeignKey("SellerGuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GuildProperty");

                    b.Navigation("SellerGuild");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildInvite", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithMany("Invites")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Character", "InviteeCharacter")
                        .WithMany()
                        .HasForeignKey("InviteeCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Character", "InviterCharacter")
                        .WithMany()
                        .HasForeignKey("InviterCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("InviteeCharacter");

                    b.Navigation("InviterCharacter");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildMember", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildProperty", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithOne("Property")
                        .HasForeignKey("Myria.Server.Realm.Models.GuildProperty", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildRookie", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithMany("Rookies")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Myria.Server.Realm.Models.Character", "RecruiterCharacter")
                        .WithMany()
                        .HasForeignKey("RecruiterCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Guild");

                    b.Navigation("RecruiterCharacter");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildRoom", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.GuildProperty", "GuildProperty")
                        .WithMany("Rooms")
                        .HasForeignKey("GuildPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildProperty");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildSettings", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithOne("Settings")
                        .HasForeignKey("Myria.Server.Realm.Models.GuildSettings", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildTreasury", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Guild", "Guild")
                        .WithOne("Treasury")
                        .HasForeignKey("Myria.Server.Realm.Models.GuildTreasury", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.PlayerShop", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.Character", "OwnerCharacter")
                        .WithMany()
                        .HasForeignKey("OwnerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerCharacter");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.PlayerShopItem", b =>
                {
                    b.HasOne("Myria.Server.Realm.Models.PlayerShop", "PlayerShop")
                        .WithMany("Items")
                        .HasForeignKey("PlayerShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerShop");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Character", b =>
                {
                    b.Navigation("ActiveQuests");

                    b.Navigation("ClassXp");

                    b.Navigation("CombinedSkills");

                    b.Navigation("CompletedQuests");

                    b.Navigation("CompositeSkills");

                    b.Navigation("InventoryItems");

                    b.Navigation("Jobs");

                    b.Navigation("KnownRunes");

                    b.Navigation("RepeatableQuests");

                    b.Navigation("RoomGatheringStatus");

                    b.Navigation("RuneDictionary");

                    b.Navigation("SkillSlots");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCombinedSkill", b =>
                {
                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterCompositeSkill", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.CharacterKnownRune", b =>
                {
                    b.Navigation("AddedWords");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.Guild", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Deposit");

                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("Property");

                    b.Navigation("Rookies");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Treasury")
                        .IsRequired();
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.GuildProperty", b =>
                {
                    b.Navigation("Listing");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Myria.Server.Realm.Models.PlayerShop", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
